<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>ServiceTrayMonitor</AssemblyName>
    <RootNamespace>ServiceTrayMonitor</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>process_monitor_icon.ico</ApplicationIcon>
    <StartupObject>ServiceTrayMonitor.Program</StartupObject>
    <PackageIcon>process_monitor_icon_preview_128.png</PackageIcon>
    <ApplicationHighDpiMode>PerMonitorV2</ApplicationHighDpiMode>
    <Version>1.0.1</Version>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Setup\**" />
    <EmbeddedResource Remove="Setup\**" />
    <None Remove="Setup\**" />
    <Compile Remove="Tests\**" />
    <EmbeddedResource Remove="Tests\**" />
    <None Remove="Tests\**" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="ServiceTrayMonitor.Tests" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="process_monitor_icon.ico">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Update="process_monitor_icon_preview_128.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>

</Project>
